export const prompt =
  "From the above file, give me these details:\n\n1. **Invoice Details:**\n   - `customerName`\n   - `invoiceDate`\n   - `totalAmount`\n   - `tax`\n\n2. **Product Details:**\n   For each product, include:\n   - `name`\n   - `quantity`\n   - `unitPrice`\n   - `tax`\n   - `priceWithTax`\n\n3. **Customer Details:**\n   - `customerName`\n   - `phoneNumber`\n   - `totalPurchaseAmount`\n\nValidate all extracted data for completeness and accuracy. Return the output in json format. If any information is missing, mark the value as `null` and specify why in a `notes` field.";

export const prompt1 =
  "From the above file, give me these details:\n\n1. **Invoice Details:**\n   - `customerName`\n   - `invoiceDate`\n   - `totalAmount`\n   - `tax`\n\n2. **Product Details:**\n   For each product, include:\n   - `serialNumber` (if available)\n   - `uniqueId` (generated for each product)\n   - `name`\n   - `quantity`\n   - `unitPrice`\n   - `tax`\n   - `priceWithTax`\n\n3. **Customer Details:**\n   - `customerName`\n   - `phoneNumber`\n   - `totalPurchaseAmount`\n\nValidate all extracted data for completeness and accuracy. Return the output in json format. If any information is missing, mark the value as `null` and specify why in a `notes` field.";

export const prompt2 =
  "From the above file, give me these details:\n\n1. **Invoice Details:**\n   - `customerName`\n   - `invoiceDate`\n   - `totalAmount`\n   - `tax`\n\n2. **Product Details:**\n   For each product, include:\n   - `serialNumber` (if available)\n   - `uniqueId` (generated for each product)\n   - `name`\n   - `quantity`\n   - `unitPrice`\n   - `tax`\n   - `priceWithTax`\n\n3. **Customer Details:**\n   - `uniqueId` (generated for each customer)\n   - `customerName`\n   - `phoneNumber`\n    - `totalPurchaseAmount`\n\nValidate all extracted data for completeness and accuracy. Return the output in json format. If any information is missing, mark the value as `null`.";

export const prompt3 =
  "From the above file, give me these details:\n\n1. **Invoice Details:**\n   - `customerName`\n   - `invoiceDate`\n   - `totalAmount`\n   - `tax`\n\n2. **Product Details:**\n   For each product, include:\n   - `serialNumber` (if available)\n   - `uniqueId` (generated for each product)\n   - `name`\n   - `quantity`\n   - `unitPrice`\n   - `tax`\n   - `priceWithTax`\n\n3. **Customer Details:**\n   - `uniqueId` (generated for each customer)\n   - `customerName`\n   - `phoneNumber`\n   - `totalPurchaseAmount`\n\nIf the `customerName` in the Invoice Details matches the `customerName` in the Customer Details, assign the same `uniqueId` to both sections.\n\nValidate all extracted data for completeness and accuracy. Return the output in JSON format. If any information is missing, mark the value as `null`.";

export const prompt4 =
  "From the above file, give me these details:\n\n1. **Invoice Details:**\n   - `customerName` or `clientName` or `buyerName`\n   - `invoiceDate` or `dateOfInvoice` or `issueDate`\n   - `totalAmount` or `amountDue` or `invoiceTotal`\n   - `tax` or `taxAmount` or `vatAmount`\n\n2. **Product Details:**\n   For each product, include:\n   - `serialNumber` or `itemNumber` or `productCode` (if available)\n   - `uniqueId` (generated for each product)\n   - `name` or `productName` or `itemDescription`\n   - `quantity` or `itemQuantity` or `units`\n   - `unitPrice` or `pricePerUnit` or `unitCost`\n   - `tax` or `productTax` or `vat`\n   - `priceWithTax` or `totalPriceWithTax`\n\n3. **Customer Details:**\n   - `uniqueId` (generated for each customer)\n   - `customerName` or `clientName` or `buyerName`\n   - `phoneNumber` or `contactNumber` or `mobile`\n   - `totalPurchaseAmount` or `totalSpent` or `totalAmountSpent`\n\nValidate all extracted data for completeness and accuracy. Return the output in JSON format. If any information is missing, mark the value as `null`.";

export const prompt5 =
  "From the above file, give me these details:\n\n1. **Invoice Details:**\n   - `customerName` or `clientName` or `buyerName`\n   - `invoiceDate` or `dateOfInvoice` or `issueDate`\n   - `totalAmount` or `amountDue` or `invoiceTotal`\n   - `tax` or `taxAmount` or `vatAmount`\n\n2. **Product Details:**\n   For each product, include:\n   - `serialNumber` or `itemNumber` or `productCode` (if available)\n   - `uniqueId` (generated for each product)\n   - `name` or `productName` or `itemDescription`\n   - `quantity` or `itemQuantity` or `units`\n   - `unitPrice` or `pricePerUnit` or `unitCost`\n   - `tax` or `productTax` or `vat`\n   - `priceWithTax` or `totalPriceWithTax`\n\n3. **Customer Details:**\n   - `uniqueId` (generated for each customer)\n   - `customerName` or `clientName` or `buyerName`\n   - `phoneNumber` or `contactNumber` or `mobile` or `ph:`\n   - `totalPurchaseAmount` or `totalSpent` or `totalAmountSpent`\n\nValidate all extracted data for completeness and accuracy. Return the output in JSON format. If any information is missing, mark the value as `null`.";

export const prompt6 =
  "From the above file, give me these details:\n\n1. **Invoice Details:**\n   - `customerName` or `clientName` or `buyerName`\n   - `invoiceDate` or `dateOfInvoice` or `issueDate`\n   - `totalAmount` or `amountDue` or `invoiceTotal`\n   - `tax` or `taxAmount` or `vatAmount`\n\n2. **Product Details:**\n   For each product, include:\n   - `serialNumber` or `itemNumber` or `productCode` (if available)\n   - `uniqueId` (generated for each product)\n   - `name` or `productName` or `itemDescription`\n   - `quantity` or `itemQuantity` or `units`\n   - `unitPrice` or `pricePerUnit` or `unitCost`\n   - `tax` or `productTax` or `vat`\n   - `priceWithTax` or `totalPriceWithTax`\n\n3. **Customer Details:**\n   - `uniqueId` (generated for each customer)\n   - `customerName` or `clientName` or `buyerName`\n   - `phoneNumber` or `contactNumber` or `mobile` or `ph:`\n   - `gstno` or `gstNumber` or `gstId` or `GSTIN`\n   - `totalPurchaseAmount` or `totalSpent` or `totalAmountSpent`\n\nValidate all extracted data for completeness and accuracy. Return the output in JSON format. If any information is missing, mark the value as `null`.";

export const prompt7 =
  "From the above file, give me these details:\n\n1. **Invoice Details:**\n   - `customerName` or `clientName` or `buyerName`\n   - `invoiceDate` or `dateOfInvoice` or `issueDate`\n   - `totalAmount` or `amountDue` or `invoiceTotal`\n   - `tax` or `taxAmount` or `vatAmount`\n\n2. **Product Details:**\n   For each product, include:\n   - `serialNumber` or `itemNumber` or `productCode` (if available)\n   - `uniqueId` (generated for each product)\n   - `name` or `productName` or `itemDescription`\n   - `quantity` or `itemQuantity` or `units`\n   - `unitPrice` or `pricePerUnit` or `unitCost`\n   - `tax` or `productTax` or `vat`\n   - `priceWithTax` or `totalPriceWithTax`\n\n3. **Customer Details:**\n   - `uniqueId` (generated for each customer)\n   - `customerName` or `clientName` or `buyerName`\n   - `phoneNumber` or `contactNumber` or `mobile` or `ph:`\n   - `gstno` or `gstNumber` or `gstId`\n   - `email` or `emailAddress` or `contactEmail`\n   - `totalPurchaseAmount` or `totalSpent` or `totalAmountSpent`\n\nValidate all extracted data for completeness and accuracy. Return the output in JSON format. If any information is missing, mark the value as `null`.";
